### ISSUE TITLE
Custom Avalanche Dashboard

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2134] opened 2024-02-02 21:36 UTC
### User Story:
As an Avalanche program owner
I want to have a customized Passport experience for my end users
So that I can continue our branding, make it understandable, and make it easy for my users to donate through Gitcoin grants.

### Acceptance Criteria
GIVEN a user goes to the /#/dahsboard/avalanche link
WHEN they arrive on the site
THEN they receive the custom ava experience

The URL for the custom dashboard
https://passport.gitcoin.co/#/dashboard/avalanche

#### Product & Design Links:

[Avalanche custom component](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=6934-1519&mode=design&t=bMJDhr9gJDM1zKUy-0)

Body Text: The Avalanche Community Grant Rounds require you to achieve a score greater than 25 to qualify for voting. The only way to reach this score is to complete identification via Civic or Holonym.

Smaller sub_text / body text - "You can join this group on telegram if you have any questions or need support: (Link)"

Splash page will be updated for ALL custom URLs to:
- drop the 'Ethereum' on the button so that it says 'Sign in'
- drop the Ethereum logo on the button 

#### Open Questions:

- [ ] Whether the team wants / needs a tooltip and if so what the tool tip links back to
- [ ] Link to return to the Avalanche Grants

**Comment by nutrina** [comment] 2024-02-05 20:23
This seems a duplicate of https://github.com/gitcoinco/passport/issues/1992
regarding the open question: that is an additional 5 SP

**Comment by Jeremy-Gitcoin** [comment] 2024-02-05 22:22
@nutrina The difference between the two is #1992 is meant for the long term / ability for anyone on the team to make these without Engineering effort and this one is just creating the custom Avax dashboard

**Comment by lucianHymer** [comment] 2024-02-20 13:50
Waiting for confirmation on where the two links (join Telegram and the action button) should point. Done otherwise.

**Comment by Jeremy-Gitcoin** [comment] 2024-02-20 16:38
@lucianHymer the link to the button CTA Avalanche grants = grants.avax.network

**Comment by Jeremy-Gitcoin** [comment] 2024-02-20 17:07
@lucianHymer It should be a score of 25 (sorry!)

**Comment by Jeremy-Gitcoin** [comment] 2024-02-22 18:25
@lucianHymer Ok finalized links:
Support link = https://t.me/avalanchegrants
CTA Avalanche grants = https://grants.avax.network

**Closed** 2024-02-22 20:36 UTC
