### ISSUE TITLE
Wallet2Connect Process Bugs

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1624] opened 2023-08-22 15:22 UTC
**Overview**
Users face an unresponsive state after successfully scanning the QR code and connecting via Ledger Live.

**Steps To Reproduce**

1. Scan the Wallet2Connect QR code.
2. Connect via Ledger Live.
3. Observe the browser screen's behavior.

**Observed  behavior**
After connecting, the browser screen changes to an unresponsive state. The console log view is also not functioning as expected.

**Expected behavior**
Smooth connection process without any unresponsive screens or errors.

**Screenshots**

**Additional context**
Support's repeated advice to clear caches doesn't resolve the issue.

**Comment by nutrina** [comment] 2023-08-25 11:43
I was not able to reproduce this, hence closing this.
We do have connections issues with ledger (cause by the fact that we do not use WalletConnect 2), but these should be covered by: https://github.com/gitcoinco/passport/issues/1623

**Closed by nutrina** 2023-08-25 11:43 UTC
