### ISSUE TITLE
Create VPC endpoint for ECR

### ISSUE THREAD

**Issue by larisa17** [gitcoinco/passport#2258] opened 2024-03-04 14:36 UTC
A possible solution to avoid high costs when a task can't start is to have a VPC endpoint for the ECR service

**Comment by nutrina** [comment] 2024-03-11 14:19
This is duplicate of: https://github.com/gitcoinco/passport/issues/2279#issue-2178349121

**Closed by nutrina** 2024-03-11 14:19 UTC
