### ISSUE TITLE
[BUG] Staked GTC not visible

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/passport#1819] opened 2023-10-27 13:43 UTC
**Overview**
Staked GTC in Season 18 is not visible on the user's dashboard. 

**Steps To Reproduce**
1. Go to https://www.staking.passport.gitcoin.co/StakeDashboard
2. Click on Season 18 at the bottom of the page
3. Users who staked on Season 18 are not able to see the GTC nor unstake them

**Observed  behavior**
Users who staked on Season 18 are not able to view their GTC nor unstake the GTC on the dashboard.

**Expected behavior**
Users should be able to view their staked GTC and ability to unstake them.

**Screenshots**
![image](https://github.com/gitcoinco/passport/assets/92294305/10133599-a1c4-4bdc-8af8-32dc2ac2631a)

**Additional context**
these is for self stake: https://etherscan.io/tx/0x1df9c1d65a4aee10f265c693120f169c0c12e28e53faa44526c9866b3e8359f1
Community stake: https://etherscan.io/tx/0x7e5d59d7580e29bf75ca8ec904f1cf795d20a96d253e3ffa101e516f3ac99516

**Comment by YukiPL** [comment] 2023-10-27 13:43
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66266?view=List

**Comment by YukiPL** [comment] 2023-10-27 13:44
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66265?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:28
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66279?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:29
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66285?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:29
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66282?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:29
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66278?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:29
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66277?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:29
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66276?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:29
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66275?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:30
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66273?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:30
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66274?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:30
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66284?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:30
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66271?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:30
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66272?view=List

**Comment by YukiPL** [comment] 2023-10-28 07:30
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66270?view=List

**Comment by YukiPL** [comment] 2023-10-28 08:16
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/66286?view=List

**Comment by YukiPL** [comment] 2023-10-28 10:15
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/66287?view=List

**Comment by YukiPL** [comment] 2023-10-28 10:16
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66288?view=List

**Comment by YukiPL** [comment] 2023-10-28 10:16
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66289?view=List

**Comment by YukiPL** [comment] 2023-10-28 11:47
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6471950/conversation/66291?view=List

**Comment by YukiPL** [comment] 2023-10-28 13:43
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/66295?view=List

**Comment by YukiPL** [comment] 2023-10-28 13:45
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66269?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:18
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/66318?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:19
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66316?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:19
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66315?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:19
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66314?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:19
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66312?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:19
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66307?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:19
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66305?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:19
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66304?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:20
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66297?view=List

**Comment by YukiPL** [comment] 2023-10-29 10:20
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66298?view=List

**Comment by YukiPL** [comment] 2023-10-29 17:03
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66324?view=List

**Comment by YukiPL** [comment] 2023-10-29 17:03
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66330?view=List

**Comment by YukiPL** [comment] 2023-10-29 17:04
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66325?view=List

**Comment by YukiPL** [comment] 2023-10-29 17:04
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66323?view=List

**Comment by YukiPL** [comment] 2023-10-29 17:04
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66322?view=List

**Comment by YukiPL** [comment] 2023-10-29 17:04
https://app.intercom.com/a/inbox/xaafeyri/inbox/view/108737/conversation/66332?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:43
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66359?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:48
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66299?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:57
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66334?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:57
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66335?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:57
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66345?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:57
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66337?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:58
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66340?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:58
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66341?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:58
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66343?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:58
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66346?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:59
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66353?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:59
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66356?view=List

**Comment by YukiPL** [comment] 2023-10-30 07:59
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66352?view=List

**Comment by YukiPL** [comment] 2023-10-30 08:00
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66344?view=List

**Comment by YukiPL** [comment] 2023-10-30 08:00
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66361?view=List

**Comment by YukiPL** [comment] 2023-10-30 08:02
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66349?view=List

**Comment by digitalmnt** [comment] 2023-10-31 23:16
@YukiPL could you please have the user's give it another try? From what I'm seeing the RPC url was not present causing the season 18 requests to fail. I added this back in and things should be functioning as intended. Thanks!

**Comment by YukiPL** [comment] 2023-11-01 10:32
@digitalmnt Thank you. I will let you know if anyone has problem.

**Comment by digitalmnt** [comment] 2023-11-01 22:05
Thanks Yuki!

**Comment by lucianHymer** [comment] 2023-11-14 19:28
@YukiPL The fix for this is released! And now we aren't depending on the subgraph, so our staking app should be a lot more reliable.

**Closed by lucianHymer** 2023-11-14 19:28 UTC
